---
- name:  Test | To show firewalld Drop Zone Setting
  shell: firewall-cmd --list-all
  become: yes
  register: show_firewall

- debug: msg="{{ show_firewall.stdout_lines }}"

- name:  Test | To show routes propagated through bgp from AVW Site
  shell: |
    echo "All Routes"
    /usr/bin/vtysh -c "show ip route json" | /usr/bin/jq .[][].prefix
    echo "BGP only"
    /usr/bin/vtysh -c "show ip route bgp json" | /usr/bin/jq .[][].prefix
  register: result_ip_route

- debug: msg="{{ result_ip_route.stdout_lines }}"

- name:  Test | To show BGP Neighbor (to AVW Site) Connection Status
  shell: /usr/bin/vtysh -c "show ip bgp neighbor json" | /usr/bin/jq .[].bgpState
  register: result_vtysh_bgp_status

- debug: msg="{{ result_vtysh_bgp_status.stdout_lines }}"

- name:  Test | Ping App Server
  shell: /usr/bin/ping -c 10 {{ serverIp }}
  register: result_ping

- debug: msg="{{ result_ping.stdout_lines }}"

- name:  Test | Run iperf3 to App Server
  shell: /usr/bin/iperf3 -c {{ serverIp }}
  register: result_iperf

- debug: msg="{{ result_iperf.stdout_lines }}"
